name: Mirror to GitLab and Run GitLab CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      # Semua variabel yang dibutuhkan oleh action
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_HOSTNAME: ${{ secrets.GITLAB_HOSTNAME }}
      GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
      GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
      GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
      BRANCH: ${{ secrets.GITLAB_BRANCH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Add GitLab remote as 'mirror'
        run: |
          # Jika GITLAB_REPO bernilai "https://gitlab.com/aditlfp/e_sppd.git",
          # perintah berikut akan menambahkan remote "mirror" dengan kredensial.
          REMOTE_URL="https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@$(echo '${{ secrets.GITLAB_REPO }}' | sed 's#https://##')"
          echo "Adding remote mirror: $REMOTE_URL"
          git remote add mirror "$REMOTE_URL"

      - name: Mirror to GitLab and run GitLab CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@0.2
