name: Deploy Laravel ke Jagoan Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Pastikan job tidak berjalan lebih dari 10 menit agar tidak hang
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Fast FTP
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Daftar file/folder yang tidak perlu diupload
          exclude: |
            node_modules/**
            .git/**
            .github/**
            README.md
            .env
