name: Mirror to GitLab and Run GitLab CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      # Semua variabel yang dibutuhkan oleh action
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_HOSTNAME: ${{ secrets.GITLAB_HOSTNAME }}
      GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
      GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
      GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
      BRANCH: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Add GitLab remote as 'mirror'
        run: |
          echo "BRANCH is set to: '$BRANCH'"
          REMOTE_URL="https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@$(echo "$GITLAB_REPO" | sed 's#https://##')"
          echo "Adding remote mirror: $REMOTE_URL"
          git remote add mirror "$REMOTE_URL" || git remote set-url mirror "$REMOTE_URL"
          git fetch mirror

      - name: Rebase local branch on top of remote 'mirror'
        run: |
          BRANCH=${BRANCH:-main}
          echo "Rebasing local '$BRANCH' on top of remote mirror '$BRANCH' using ours strategy..."
          # Rebase sehingga semua commit lokal akan diterapkan di atas commit remote.
          git rebase mirror/"$BRANCH" -X ours

      - name: Push to GitLab without force push
        run: |
          BRANCH=${BRANCH:-main}
          echo "Pushing local branch '$BRANCH' to remote 'mirror'..."
          git push mirror "$BRANCH"

      - name: Mirror to GitLab and run GitLab CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@0.2
