name: Mirror to GitLab and Run GitLab CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      # Semua variabel yang dibutuhkan oleh action
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
      GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
      BRANCH: ${{ secrets.GITLAB_BRANCH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Mirror to GitLab and run GitLab CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@0.2
