name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          echo "Menginstal paket zip..."
          sudo apt-get update && sudo apt-get install -y zip
          echo "Install dependency Node.js..."
          npm install
          echo "Menjalankan build..."
          npm run build
          echo "Mengompres folder node_modules..."
          zip -r node_modules.zip node_modules

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install PHP dependencies
        run: |
          echo "Menginstal paket zip..."
          sudo apt-get install -y zip unzip
          echo "Install dependency PHP..."
          composer install --no-dev --prefer-dist
          echo "Mengompres folder vendor..."
          zip -r vendor.zip vendor

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            node_modules.zip
            vendor.zip
            public/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./

      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp unzip zip

      - name: Deploy files via FTP
        run: |
          echo "Mulai deploy via FTP..."
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; 
                   mirror -R --verbose=4 --exclude node_modules --exclude .git --exclude .github --exclude vendor --exclude node_modules.zip --exclude vendor.zip ./ ../../"

          echo "Upload file node_modules.zip dan vendor.zip..."
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; 
                   put node_modules.zip -o ../../node_modules.zip"
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; 
                   put vendor.zip -o ../../vendor.zip"

          echo "Menjalankan unzip node_modules di server..."
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; 
                   lcd ../../; 
                   !unzip -o node_modules.zip -d node_modules; 
                   !rm node_modules.zip"

          echo "Menjalankan unzip vendor di server..."
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; 
                   lcd ../../; 
                   !unzip -o vendor.zip -d vendor; 
                   !rm vendor.zip"

    env:
      FTP_USER: ${{ secrets.FTP_USER }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_HOST: ${{ secrets.FTP_HOST }}
