name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          npm install
          npm run build

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install PHP dependencies
        run: |
          sudo apt-get install -y zip unzip
          composer install --no-dev --prefer-dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            public/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./

      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy files via FTP
        run: |
          echo "Starting FTP deploy..."
          lftp -c "set ssl:verify-certificate no; \
                   open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; \
                   mirror -R --verbose=4 --exclude node_modules --exclude .git --exclude .github --exclude tests ./ public_html; bye"
    env:
      FTP_USER: ${{ secrets.FTP_USER }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_HOST: ${{ secrets.FTP_HOST }}
